// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: keyword_spotting_ui

#include "../ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dbaChart = lv_chart_create(ui_Home);
lv_obj_set_width( ui_dbaChart, 172);
lv_obj_set_height( ui_dbaChart, 209);
lv_obj_set_x( ui_dbaChart, 15 );
lv_obj_set_y( ui_dbaChart, 16 );
lv_obj_set_align( ui_dbaChart, LV_ALIGN_CENTER );
lv_chart_set_type( ui_dbaChart, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_dbaChart, LV_CHART_AXIS_PRIMARY_Y, 20, 100);
lv_chart_set_axis_tick( ui_dbaChart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_dbaChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_dbaChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);



ui_Label1 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 47 );
lv_obj_set_y( ui_Label1, -112 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"dB(A)");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -89 );
lv_obj_set_y( ui_Label2, -98 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"dB(A)");

ui_dbaValue = lv_label_create(ui_Home);
lv_obj_set_width( ui_dbaValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dbaValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dbaValue, -115 );
lv_obj_set_y( ui_dbaValue, -233 );
lv_obj_set_align( ui_dbaValue, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_dbaValue,"100");
lv_obj_set_style_text_color(ui_dbaValue, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dbaValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dbaValue, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

}
